### ISSUE TITLE
Checklist 2 Compounding

### ISSUE THREAD

**Issue by dimztimz** [nuspell/nuspell#13]
- [x] Decipher v1 code
- [x] Simple compuding with BREAK
- [x] Advanced compounding. Has 3 major modes:
    - [x] With flags only (COMPOUNDFLAG, COMPOUNDMIDDLE, ...) + CHECKCOMPOUND patterns without replacing.
   - [x] With flags only + CHECKCOMPOUND patterns with replacing
   - [x] COMPOUNDRULE

**Comment by dimztimz** [comment]
This is finished some time ago. Closing now.
