### ISSUE TITLE
Checklist 3 - Testing

### ISSUE THREAD

**Issue by dimztimz** [nuspell/nuspell#22]
## 3. Testing

- [x] Unit testing
    - [x] Reuse old unit tests via CLI interface
    - [x] Write new C++ unit tests for new code only, don't test old code, it already has tests.
    - [x] Report code coverage unit tests
- [x] Regression testing
    - [x] select, download, extract and report Ubuntu Hunspell language support packages
    - [x] select, download, extract and report Ubuntu word list packages
    - [x] gather words, split on separators, filter characters for each language
    - [x] check spelling and report correctness and speed for Hunspell
    - [x] optmize Hunspell for regression testing with extra parameter
    - [x] check spelling and report correctness and speed for Nuspell commits
    - [x] report regression for correctness with Nuspell also with regard to Hunspell reference
    - [x] report regression for speed with Nuspell also with regard to Hunspell reference
