### ISSUE TITLE
Checklist 4 - Suggestions

### ISSUE THREAD

**Issue by dimztimz** [nuspell/nuspell#23]
- [x] Understand v1 code and give some docs on it
- [x] Implement the standard algorithm for suggestions (TRY).
- [x] Add the keyboard closeness factor to the algorithm (KEY).
- [x] Add support for manually written replacements of character sequences (REP).
- [x] Add the character closeness factor (MAP).
- [x] Add the phonetic closeness factor (PHONET).
- [x] Write suggestion tests.
