### ISSUE TITLE
Checklist 1 basic checking and affixing

### ISSUE THREAD

**Issue by dimztimz** [nuspell/nuspell#5]
## 1. Documenting old code

Write the comments in the libreoffice docs. Use examples. If something is not clear,
run a debug session with test data. Even better, run a "debug session" in
your head and write state on paper.

- [x] HunspellImpl::spell
	- [x] HunspellImpl::checksharps
	- [x] HunspellImpl::checkword
- [x] Affixmgr::check_affix
	- [x] AffixMgr::prefix_check
	- [x] AffixMgr::prefix_check_twosfx
	- [x] AffixMgr::suffix_check
	- [x] AffixMgr::suffix_check_twosfx
	- [x] PfxEntry::checkword
	- [x] PfxEntry::check_twosfx
	- [x] SfxEntry::checkword
	- [x] SfxEntry::check_twosfx

## 2. Implementation

- [x] spell
	- [x] spell_break
	- [x] spell_casing
	- [x] spell_uppercase
	- [x] spell_titlecase
	- [x] checkword
	- [x] homonym support (use multimap instead of map)
	- [x] hidden uppercased homonym for mixed case wrods
- [x] affixing
	- [x] strip only suffix
	- [x] strip only prefix
	- [x] strip prefix then suffix
	- [x] strip suffix then prefix
	- [x] strip two suffixes
	- [x] strip two prefixes (COMPLEXPREFIXES)
	- [x] strip prefix, suffix, suffix
	- [x] strip suffix, prefix, suffix
	- [x] strip suffix, suffix, prefix
	- [x] strip suffix, prefix, prefix (COMPLEXPREFIXES)
	- [x] strip prefix, suffix, prefix (COMPLEXPREFIXES)
	- [x] strip prefix, prefix, suffix (COMPLEXPREFIXES)

**Comment by dimztimz** [comment]
Updated checklist, 1 and 2 level affixing is done.

**Comment by dimztimz** [comment]
Updated checklist, 3 level affixing is done.

**Comment by dimztimz** [comment]
Updated checklist on casing
